version: '3.8'

services:
  chatterbox-zai:
    build: .
    container_name: chatterbox_zai_tts
    expose:
      - "8080"
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - CHATTERBOX_MULTILINGUAL_T3_MODEL=v3
    volumes:
      - ./static/audio_output:/app/static/audio_output
      - ./static/uploads:/app/static/uploads
      - hf_cache:/root/.cache/huggingface
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-guideitsol-http.entrypoints=http"
      - "traefik.http.routers.chat-guideitsol-http.rule=Host(`chat.guideitsol.in`)"
      - "traefik.http.routers.chat-guideitsol-http.middlewares=redirect-to-https"
      - "traefik.http.routers.chat-guideitsol-https.entrypoints=https"
      - "traefik.http.routers.chat-guideitsol-https.rule=Host(`chat.guideitsol.in`)"
      - "traefik.http.routers.chat-guideitsol-https.tls=true"
      - "traefik.http.routers.chat-guideitsol-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.chat-guideitsol.loadbalancer.server.port=8080"
    restart: unless-stopped

networks:
  coolify:
    external: true

volumes:
  hf_cache:

